version: '3'
services:
  myapp:
    build: .
    volumes:
      - myapp_data:/app/data
    ports:
      - "5000:5000"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"

volumes:
  myapp_data:
