version: '3'
services:
  myapp:
    build: .
    environment:
      S3_ENDPOINT: http://localstack:4566
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
